# models/sources.yml

version: 3

sources:
  - name: STG
    database: stg
    schema: public
    tables:
      - name: customer
        description: "This table contains customer information, including personal details and account balance."
      - name: nation
      - name: orders
